### ISSUE TITLE
SmartOS (Joyent/Nodejitsu)

### ISSUE THREAD

**Issue by sberryman** [NodeFly/node-nodefly-gcinfo#1]
I wrote you guys about the issue trying to deploy on nodejitsu where this package fails to compile. All I can get is an error from the nodejitsu deploy script.

Nodejitsu runs on Joyent's smartos (sunos) which seems to have quite a few linker issues for compiled modules. I'm creating the issue to make it easier for me to track. @jacobgroundwater has already responded to the e-mail requesting support.

I look forward to trying this out with a few of my apps, can't wait to see what my apps are doing in real time!

Deploy output:

``` shell
info:    Creating snapshot 0.1.52
info     Uploading: [                             ] 1%
info:    Updating app teeleader-api
info:    Activating snapshot 0.1.52 for teeleader-api
info:    Starting app teeleader-api
error:   Error running command deploy
error:   Nodejitsu Error (500): Internal Server Error
error:   
error:   There was an error while attempting to start the app
error:   Error spawning drone
error:   Script prematurely exited
error:   
error:   This type of error is usually a user error.
error:   Error output from app:
error:   
error:   module.js:340
error:       throw err;
error:             ^
error:   Error: Cannot find module './compiled/sunos/x64/v0.8.12/gcinfo'
error:       at Function.Module._resolveFilename (module.js:338:15)
error:       at Function.Module._load (module.js:280:25)
error:       at Module.require (module.js:362:17)
error:       at require (module.js:378:17)
error:       at Object.<anonymous> (/opt/haibu/apps/sberryman/teeleader-api/package/node_modules/nodefly/node_modules/nodefly-gcinfo/index.js:57:18)
error:       at Module._compile (module.js:449:26)
error:       at Object.Module._extensions..js (module.js:467:10)
error:       at Module.load (module.js:356:32)
error:       at Function.Module._load (module.js:312:12)
error:       at Module.require (module.js:362:17)
help:    For help with this error contact Nodejitsu Support:
help:      webchat: <http://webchat.nodejitsu.com/>
help:          irc: <irc://chat.freenode.net/#nodejitsu>
help:        email: <support@nodejitsu.com>
help:    
help:      Copy and paste this output to a gist (http://gist.github.com/)
info:    Nodejitsu not ok
```

**Comment by groundwater** [comment]
64 bit SunOS version has been added

https://github.com/NodeFly/node-nodefly-gcinfo/commit/8f9faccf67cd69efb12b125efdb4b0c2b1fe756e

The package has been updated on [npm](https://npmjs.org/package/nodefly-gcinfo)

Please note that the nodefly package has a ~version dependency on `nodefly-gcinfo`, so until the nodefly agent is updated npm may not realize it needs to update the gcinfo package.

Try removing the package `node_modules/nodefly/node_modules/nodefly-gcinfo` and running `npm install` again.

**Comment by sberryman** [comment]
New error:

``` bash
error:   Error running command deploy
error:   Nodejitsu Error (500): Internal Server Error
error:   
error:   There was an error while attempting to start the app
error:   Error spawning drone
error:   Script prematurely exited
error:   
error:   This type of error is usually a user error.
error:   Error output from app:
error:   
error:   module.js:485
error:     process.dlopen(filename, module.exports);
error:             ^
error:   Error: ld.so.1: node: fatal: /opt/haibu/apps/sberryman/teeleader-worker/package/node_modules/nodefly/node_modules/nodefly-gcinfo/compiled/sunos/x64/v0.8.12/gcinfo.node: wrong ELF class: ELFCLASS32
error:       at Object.Module._extensions..node (module.js:485:11)
error:       at Module.load (module.js:356:32)
error:       at Function.Module._load (module.js:312:12)
error:       at Module.require (module.js:362:17)
error:       at require (module.js:378:17)
error:       at Object.<anonymous> (/opt/haibu/apps/sberryman/teeleader-worker/package/node_modules/nodefly/node_modules/nodefly-gcinfo/index.js:57:18)
error:       at Module._compile (module.js:449:26)
error:       at Object.Module._extensions..js (module.js:467:10)
error:       at Module.load (module.js:356:32)
error:       at Function.Module._load (module.js:312:12)
help:    For help with this error contact Nodejitsu Support:
help:      webchat: <http://webchat.nodejitsu.com/>
help:          irc: <irc://chat.freenode.net/#nodejitsu>
help:        email: <support@nodejitsu.com>
help:    
help:      Copy and paste this output to a gist (http://gist.github.com/)
info:    Nodejitsu not ok
```

**Comment by groundwater** [comment]
Okay, I'm gonna make this a priority, especially since `Nodejitsu not ok` is perhaps the greatest error line ever.

**Comment by sberryman** [comment]
Thanks, I'm more than happy to keep testing

**Comment by groundwater** [comment]
So... It looks like Nodejitsu is reporting that it is 64bit, while it's actually 32bit. I'm sure this is an easy fix, i'm using `process.arch` to determine which architecture to load.

Let me ponder this for a while.

**Comment by sberryman** [comment]
I was just talking with support and they claimed they are 64bit. 

```
blakmatrix: do you know if the drones are 32bit or 64bit?
blakmatrix: sberryman: 64
sberryman: blakmatrix: process.arch is reporting 64bit
sberryman: and you are 100% positive they are 64bit?
blakmatrix: sberryman: I am 100% possitive that drones are supposed to be 64-bit lol, if they are not then they will be destroyed
```

**Comment by groundwater** [comment]
@sberryman I messed up, and got led down a rabbit hole. To compile the 64bit module I used a `smartosplus64` box, which turns out compiled a 32 bit module.

I have tested the update on both 32bit and 64bit machines now, please give it a try.

**Comment by sberryman** [comment]
Can you publish to NPM?

**Comment by groundwater** [comment]
It should be published. Sometimes NPM displays the old version for a few minutes after publishing, but the command line should work.

I tried a test deployment to nodejitsu and it worked.

**Comment by sberryman** [comment]
Now I'm seeing this error:

```
[11/08 12:56:18 PST] /opt/haibu/apps/sberryman/teeleader-api/package/node_modules/nodefly/lib/tiers.js:15
[11/08 12:56:18 PST]    data._ts = nf.millis();
[11/08 12:56:18 PST]                  ^
[11/08 12:56:18 PST] TypeError: Cannot call method 'millis' of undefined
[11/08 12:56:18 PST]     at Timer.<anonymous> (/opt/haibu/apps/sberryman/teeleader-api/package/node_modules/nodefly/lib/tiers.js:15:16)
[11/08 12:56:18 PST]     at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
[11/08 12:56:19 PST] SORRY: the nodefly agent does not yet work on your platform(solaris).
```

**Comment by groundwater** [comment]
Oh my, we have the same report in Issue #2.

This issue has become our priority, and we will get back to you soon. Thanks for your patience.

**Comment by groundwater** [comment]
Hi, I have updated the nodefly agent. Please try installing `nodefly@0.1.9` - if that works for you I will mark the fix as stable in npm.

**Comment by sberryman** [comment]
Looks like it is working, not showing CPU Usage but everything else appears to show up. I sent you an e-mail but knowing how to remove old hosts would be great. A new hostname is generated every deploy on nodejitsu and frankly having an aggregated display for each "App" would be great.

**Comment by groundwater** [comment]
Okay, I have opened an issue here https://github.com/NodeFly/NodeFly/issues/3 for the CPU info on nodejitsu
